import Navbar from "@/components/Navbar"
import Sidebar from "@/components/Sidebar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 py-2 overflow-hidden">
        <div className="relative h-screen flex justify-start items-start ">
        <Sidebar />
        <div className="flex-1 bg-white h-[90vh] rounded-xl">
            <Navbar />
            {children}
        </div>
        </div>
      </body>
    </html>
  )
}
